---
title: "CR_Mod1_Eval"
author: "Tom Zhang"
date: "5/21/2020"
output: html_document
---

## Importing data for linear regression model
```{r}
library(tidyverse)
library(broom)
cr_s3_df_ind_left <- read_csv("data/cr_s3_df_ind_left.csv")
```


## Cleaning up data
```{r}
df_mod1 <-
  cr_s3_df_ind_left %>%
    select(-1:-5) %>%
    select(-2:-20)
```


## The model
```{r}
mod1 <- lm(leftstartingtrophies ~ ., data = df_mod1)

tidy(mod1) # coefficients
glance(mod1) # goodness of fit summary

df_mod1_aug <-
  df_mod1 %>%
    augment(mod1, data = .) %>%
    select(1, 190:196)

df_mod1_aug # comparing observed and fitted
```


## Cross-validation
```{r}
library(caret)
set.seed(2020)

# create training & testing sets
partitionRule <- createDataPartition(df_mod1$leftstartingtrophies, p = 0.7, list = FALSE)
trainingDF <- df_mod1[partitionRule,]
testingDF <- df_mod1[-partitionRule,]

# training mod
controlParameters <- trainControl(method = "cv", number = 10, savePredictions = TRUE)
trainingMod <- train(leftstartingtrophies ~ ., data = trainingDF, method = "lm", trControl = controlParameters)

# predictions
predictions <- predict(trainingMod, testingDF)

trainingMod
```


## Predictions: case 1
```{r}
# create an empty case df
caseEmpty <-
  df_mod1 %>%
    select(-1) %>%
    slice(1)

for (col in 1:ncol(caseEmpty)) {
  for (row in 1:nrow(caseEmpty)) {
    caseEmpty[row,col] = 0
  }
}

# case 1 - my deck 1
# before upgrading Dark Prince
case1 <-
  caseEmpty %>%
    mutate(
      `The Log` = 1,
      `The Log Lvl` = 11,
      Miner = 1,
      `Miner Lvl` = 11,
      `Electro Wizard` = 1,
      `Electro Wizard Lvl` = 11,
      Balloon = 1,
      `Balloon Lvl` = 13,
      `Dark Prince` = 1,
      `Dark Prince Lvl` = 12,
      Wizard = 1,
      `Wizard Lvl` = 13,
      Valkyrie = 1,
      `Valkyrie Lvl` = 13,
      `Mini P.E.K.K.A` = 1,
      `Mini PEKKA Lvl` = 13
    )

predict.lm(mod1, case1) # get 5277.632, actual 5180, residual = -97.632


# after upgrading Dark Prince
case1 <-
  caseEmpty %>%
    mutate(
      `The Log` = 1,
      `The Log Lvl` = 11,
      Miner = 1,
      `Miner Lvl` = 11,
      `Electro Wizard` = 1,
      `Electro Wizard Lvl` = 11,
      Balloon = 1,
      `Balloon Lvl` = 13,
      `Dark Prince` = 1,
      `Dark Prince Lvl` = 13,
      Wizard = 1,
      `Wizard Lvl` = 13,
      Valkyrie = 1,
      `Valkyrie Lvl` = 13,
      `Mini P.E.K.K.A` = 1,
      `Mini PEKKA Lvl` = 13
    )

predict.lm(mod1, case1) # get 5330.534
```


## Case 2
```{r}
# case 2 - Dr. Ramler's deck 3
# before upgrading Knight and Skeletons
case2 <-
  caseEmpty %>%
    mutate(
      `Baby Dragon` = 1,
      `Baby Dragon Lvl` = 11,
      `Goblin Hut` = 1,
      `Goblin Hut Lvl` = 11,
      Graveyard = 1,
      `Graveyard Lvl` = 10,
      Knight = 1,
      `Knight Lvl` = 11,
      `The Log` = 1,
      `The Log Lvl` = 11,
      Musketeer = 1,
      `Musketeer Lvl` = 13,
      Poison = 1,
      `Poison Lvl` = 11,
      Skeletons = 1,
      `Skeletons Lvl` = 10
    )

predict.lm(mod1, case2)


# after upgrading Knight and Skeletons
case2 <-
  caseEmpty %>%
    mutate(
      `Baby Dragon` = 1,
      `Baby Dragon Lvl` = 11,
      `Goblin Hut` = 1,
      `Goblin Hut Lvl` = 11,
      Graveyard = 1,
      `Graveyard Lvl` = 10,
      Knight = 1,
      `Knight Lvl` = 12,
      `The Log` = 1,
      `The Log Lvl` = 11,
      Musketeer = 1,
      `Musketeer Lvl` = 13,
      Poison = 1,
      `Poison Lvl` = 11,
      Skeletons = 1,
      `Skeletons Lvl` = 11
    )

predict.lm(mod1, case2)
```


## Case 3
```{r}
# case 2 - Dr. Ramler's deck 4
# before upgrading Electro Dragon
case3 <-
  caseEmpty %>%
    mutate(
      Bats = 1,
      `Bats Lvl` = 11,
      `Dart Goblin` = 1,
      `Dart Goblin Lvl` = 11,
      `Goblin Gang` = 1,
      `Goblin Gang Lvl` = 12,
      `Mega Knight` = 1,
      `Mega Knight Lvl` = 11,
      Miner = 1,
      `Miner Lvl` = 11,
      `Skeleton Barrel` = 1,
      `Skeleton Barrel Lvl` = 11,
      Zap = 1,
      `Zap Lvl` = 13,
      `Electro Dragon` = 1,
      `Electro Dragon Lvl` = 12
    )

predict.lm(mod1, case3)


# after upgrading Electro Dragon
case3 <-
  caseEmpty %>%
    mutate(
      Bats = 1,
      `Bats Lvl` = 11,
      `Dart Goblin` = 1,
      `Dart Goblin Lvl` = 11,
      `Goblin Gang` = 1,
      `Goblin Gang Lvl` = 12,
      `Mega Knight` = 1,
      `Mega Knight Lvl` = 11,
      Miner = 1,
      `Miner Lvl` = 11,
      `Skeleton Barrel` = 1,
      `Skeleton Barrel Lvl` = 11,
      Zap = 1,
      `Zap Lvl` = 13,
      `Electro Dragon` = 1,
      `Electro Dragon Lvl` = 13
    )

predict.lm(mod1, case3)
```
















