---
title: "Hover with ggplotly"
author: "Tom Zhang"
date: "6/17/2020"
output: html_document
---

# https://www.basjacobs.com/post/showing-images-on-hover-in-plotly-with-r/

```{r}
library(tidyverse)
library(plotly)
library(htmlwidgets)

g <- ggplot(iris, aes(x = Sepal.Length,
                      y = Petal.Length,
                      color = Species,
                      text = Species)) + geom_point()
p <- ggplotly(g, tooltip = "text") %>% partial_bundle() 

p
```

```{r}
p %>% htmlwidgets::onRender("
    function(el, x) {
      // when hovering over an element, do something
      el.on('plotly_hover', function(d) {

        // extract tooltip text
        txt = d.points[0].data.text;
        // image is stored locally
        image_location = '../*R/SLU_Fellowship_2020/Shiny/Hover_Img_Expiriment/' + txt + '.png';
                          
        // define image to be shown
        var img = {
          // location of image
          source: image_location,
          // top-left corner
          x: 0,
          y: 0,
          sizex: 0.5,
          sizey: 0.5,
          xref: 'paper',
          yref: 'paper'
        };

        // show image and annotation 
        Plotly.relayout(el.id, {
            images: [img] 
        });
      })
    }
    ")
```














