---
title: "Mod 2 Evaluation"
author: "Tom Zhang"
date: "6/8/2020"
output: html_document
---

## fitting mod2v2
## trophies ~ day + card indicators + card numeric level + (card numeric level)^2 + card interactions
```{r}
# import data
library(tidyverse)
library(broom)
cr_s3_df_ind_left <- read_csv("data/cr_s3_df_ind_left.csv")

# cleaning up data
df_mod2 <-
  cr_s3_df_ind_left %>%
    mutate(battletime = as.character(as.POSIXct(battletime, origin="2019-09-02", tz="GMT"))) %>%
    mutate(battletime = str_remove(battletime, "\\s.*")) %>%
    separate(battletime, into = c("yearMonth", "dayOfTheMonth"), sep = -2) %>%
    mutate(dayOfTheMonth = as.numeric(dayOfTheMonth)) %>%
    select(leftstartingtrophies, dayOfTheMonth, 27:214)

# mod_cardInt: trophies ~ cards + all 2-way card interactions
df_cardInt <-
  df_mod2 %>%
    select(1, 3:96)

t1_start <- Sys.time()
mod_cardInt <- lm(leftstartingtrophies ~ (.)^2, data = df_cardInt) # all 2-way interactions (7 min)
t1_end <- Sys.time()
t1_end - t1_start

# mod2v2
f2 <- as.formula(
  paste(
    "leftstartingtrophies ~",
    paste(
      c(
        paste('`', names(df_mod2)[2:190], '`', sep = ''), # day + cards + levels
        paste('I(`', names(df_mod2)[97:190], '`^2)', sep = ''), # quadratic levels
        names(coef(mod_cardInt))[-1:-95] # all 2-way card interactions
        ),
      collapse = " + "
      )
    )
  )

t2_start <- Sys.time()
mod2v2 <- lm(formula = f2, data = df_mod2) # 7 min
t2_end <- Sys.time()
t2_end - t2_start


#summary(mod2v2)
tidy(mod2v2)
glance(mod2v2)
```


## Import/process right deck
```{r}
cr_s3_df_ind_right <- read_csv("data/cr_s3_df_ind_right.csv")

df_mod2_right <-
  cr_s3_df_ind_right %>%
    mutate(battletime = as.character(as.POSIXct(battletime, origin="2019-09-02", tz="GMT"))) %>%
    mutate(battletime = str_remove(battletime, "\\s.*")) %>%
    separate(battletime, into = c("yearMonth", "dayOfTheMonth"), sep = -2) %>%
    mutate(dayOfTheMonth = as.numeric(dayOfTheMonth)) %>%
    select(rightstartingtrophies, dayOfTheMonth, 27:214)
```


# Predicting right deck trophies using mod2v2 (i.e., created from left deck)
```{r}
t3_start <- Sys.time()

df_mod2v2_aug <-
  df_mod2_right %>%
    augment(mod2v2, data = .) %>%
    select(1, 191:196)

t3_end <- Sys.time() # about 56 min
t3_end - t3_start

df_mod2v2_aug # comparing observed and fitted for right deck
```


## save prediction df
```{r}
write_csv(df_mod2v2_aug, "data/df_mod2v2_aug.csv")
```

















