---
title: "s11 eval"
output: html_document
---

# import

## import models
```{r}
library(tidyverse)
library(automl)
mod11_CLAW_4001_6600 <-
  readRDS("~/research/CR_Project_Tom/data_processed/mod_s11_ComboLastActiveWin_4001_6600.rds")

mod11_CLAW_4001_6300 <-
  readRDS("~/research/CR_Project_Tom/data_processed/mod_s11_ComboLastActiveWin_4001_6300.rds")

mod11_CLAW_4001_6000 <-
  readRDS("~/research/CR_Project_Tom/data_processed/mod_s11_ComboLastActiveWin_4001_6000.rds")
```


## imoprt df

### universal
```{r}
rarity <- read_csv("~/research/CR_Project_Tom/cr_rarity_level_adjustments.csv")

cr_cards <-
  jsonlite::fromJSON("~/research/CR_Project_Tom/clash_royale_card_info.json")$cards %>%
  select(name, rarity) %>%
  # season 1 added in Fisherman - nothing more up to season 3
  bind_rows(., tibble(name = "Fisherman", rarity = "Legendary")) %>%
  # season 4: elixir golem
  bind_rows(., tibble(name = "Elixir Golem", rarity = "Rare")) %>%
  # season 6: battle healer
  bind_rows(., tibble(name = "Battle Healer", rarity = "Rare")) %>%
  # season 7: firecracker
  bind_rows(., tibble(name = "Firecracker", rarity = "Common")) %>%
  # season 9: royal delivery
  bind_rows(., tibble(name = "Royal Delivery", rarity = "Common")) %>%
  # season 10: replaces heal with heal spirit
  mutate(name = str_replace(name, "^Heal$", "Heal Spirit"))

# reading in all lines
cr_full <- read_csv("~/research/CR_Project_Tom/data_by_season/clash_royale_matches_season_11_2020-05-04_to_2020-06-01.csv")



# combine left and right tags
df_left <- cr_full %>% select(1:7) %>% mutate()
names(df_left) <- c("id", "battletime", "arenaid",
                    "playertag", "startingtrophies", "trophychange", "deck")

df_right <- cr_full %>% select(1:3, 8:11)
names(df_right) <- c("id", "battletime", "arenaid",
                    "playertag", "startingtrophies", "trophychange", "deck")

df_combined <- bind_rows(df_left, df_right)
```


### df for 1st model: 4001-6600
```{r}
# filter only the active players based on playertag
cr_sub <-
  df_combined %>%
    group_by(playertag) %>%
    filter(n() >= 25) %>% # define active
    filter(trophychange > 0) %>% # keep winned matches
    arrange(desc(battletime)) %>%
    slice(1) %>% # only take the last match for a player
    ungroup() #187,205




# reduce vars
cr_reduced <-
  cr_sub %>%
  select(playertag, battletime, startingtrophies, trophychange, deck)


set.seed(3007)
cr <- cr_reduced %>%
  #filter(battletime > '2020-05-29') %>% # only look at the last few days in the season
  #sample_n(tbl = ., size = 20000) %>% # random sample of 20k
  filter(str_count(deck, pattern = ",") == 15) # ensures 8 card decks



# fix card/level part
xcards <-
cr %>%  
  separate_rows(deck, sep = "\\],") %>%
  separate(deck, into = c("Cards","Level"), sep = ", ") %>%
  mutate(Level = parse_number(Level),
         Cards = str_remove_all(Cards, "\\[+"),
         Cards = str_remove_all(Cards, '\\"'),
         Cards = str_trim(Cards, side = c("both"))
         ) %>%
  left_join(., cr_cards, by = c("Cards" = "name")) %>% # add rarity info
  left_join(rarity, by = "rarity") %>% # add level adjustment
  mutate(Level = Level  + level_adjustment) %>% # adjust levels
  select(-rarity, -level_adjustment, -trophychange) # reduce size of dataframe

x = model.matrix(~0 + Cards + Level, model.frame(~ ., xcards, na.action=na.pass)) # make indictor variables

#x = xcards %>%  model.matrix(~0 + Cards + Level, data = .) 

x = sweep(x[,-ncol(x)], MARGIN = 1, STATS = x[,ncol(x)], FUN = "*")

colnames(x) = str_remove_all(colnames(x), "Cards")
colnames(x) = str_replace_all(colnames(x), " ", "_")
colnames(x) = str_replace_all(colnames(x), "-", "_")

# create names for all card and card interaction terms
interactions = labels(terms(~.^2, data = x[1:10,]))

colnames(x) = paste(colnames(x),"_Level",sep = "")

deck <- 
  x %>%
  as_tibble() %>%
  mutate(tmpid = xcards$playertag) %>%
  group_by(tmpid) %>%
  summarize_if(is.numeric, sum)

rm(x) # free up memory
rm(xcards)

# put back together
cr <- cr %>%
  select(battletime, startingtrophies) %>%
  bind_cols(sign(deck[,-1])) %>%
  bind_cols(deck[,-1])

rm(deck) # free memory from deck

names(cr) = str_remove_all(names(cr), "_Level") # fix anmes
names(cr) = str_replace_all(names(cr), "1","_Level") # one more fix



# filter 4000+
# and convert battletime -> day of the month
cr <-
  cr %>%
  filter(startingtrophies >= 4001 & startingtrophies < 6600) %>%
  mutate(battletime = str_remove(battletime, "\\s.+")) %>%
  mutate(battletime = str_remove(battletime, "[:digit:]{4}-[:digit:]{2}-")) %>%
  mutate(battletime = as.numeric(battletime))
```




# predict season 11

## mod11_CLAW_4001_6600 - s11, ComboLastActiveWin, 4001-6600
```{r}
# trophies ~ dayOfTheMonth + cards + levels + levels^2 + card interactions + day interact with lvl and lvl^2

preds <- predict(mod11_CLAW_4001_6600, cr[,-2])
df1 <- tibble(trophies = cr$startingtrophies, preds = preds)
df1 <-
  df1 %>%
  mutate(resid = trophies - preds)

df1 %>%
  ggplot(., aes(x = trophies, y = resid)) +
  geom_point() +
  geom_smooth() +
  labs(
    title = "Residuals vs Trophies (S11) Using 4001-6600 S11 Combined Last Active Win",
    subtitle = "trophies ~ dayOfTheMonth + cards + levels + levels^2 + card interactions + day:lvl & lvl^2"
    ) +
  theme_bw()
```










## df for 2nd model: 4001-6300
```{r}
# filter only the active players based on playertag
cr_sub <-
  df_combined %>%
    group_by(playertag) %>%
    filter(n() >= 25) %>% # define active
    filter(trophychange > 0) %>% # keep winned matches
    arrange(desc(battletime)) %>%
    slice(1) %>% # only take the last match for a player
    ungroup() #187,205




# reduce vars
cr_reduced <-
  cr_sub %>%
  select(playertag, battletime, startingtrophies, trophychange, deck)


set.seed(3007)
cr <- cr_reduced %>%
  #filter(battletime > '2020-05-29') %>% # only look at the last few days in the season
  #sample_n(tbl = ., size = 20000) %>% # random sample of 20k
  filter(str_count(deck, pattern = ",") == 15) # ensures 8 card decks



# fix card/level part
xcards <-
cr %>%  
  separate_rows(deck, sep = "\\],") %>%
  separate(deck, into = c("Cards","Level"), sep = ", ") %>%
  mutate(Level = parse_number(Level),
         Cards = str_remove_all(Cards, "\\[+"),
         Cards = str_remove_all(Cards, '\\"'),
         Cards = str_trim(Cards, side = c("both"))
         ) %>%
  left_join(., cr_cards, by = c("Cards" = "name")) %>% # add rarity info
  left_join(rarity, by = "rarity") %>% # add level adjustment
  mutate(Level = Level  + level_adjustment) %>% # adjust levels
  select(-rarity, -level_adjustment, -trophychange) # reduce size of dataframe

x = model.matrix(~0 + Cards + Level, model.frame(~ ., xcards, na.action=na.pass)) # make indictor variables

#x = xcards %>%  model.matrix(~0 + Cards + Level, data = .) 

x = sweep(x[,-ncol(x)], MARGIN = 1, STATS = x[,ncol(x)], FUN = "*")

colnames(x) = str_remove_all(colnames(x), "Cards")
colnames(x) = str_replace_all(colnames(x), " ", "_")
colnames(x) = str_replace_all(colnames(x), "-", "_")

# create names for all card and card interaction terms
interactions = labels(terms(~.^2, data = x[1:10,]))

colnames(x) = paste(colnames(x),"_Level",sep = "")

deck <- 
  x %>%
  as_tibble() %>%
  mutate(tmpid = xcards$playertag) %>%
  group_by(tmpid) %>%
  summarize_if(is.numeric, sum)

rm(x) # free up memory
rm(xcards)

# put back together
cr <- cr %>%
  select(battletime, startingtrophies) %>%
  bind_cols(sign(deck[,-1])) %>%
  bind_cols(deck[,-1])

rm(deck) # free memory from deck

names(cr) = str_remove_all(names(cr), "_Level") # fix anmes
names(cr) = str_replace_all(names(cr), "1","_Level") # one more fix



# filter 4000+
# and convert battletime -> day of the month
cr <-
  cr %>%
  filter(startingtrophies >= 4001 & startingtrophies < 6300) %>%
  mutate(battletime = str_remove(battletime, "\\s.+")) %>%
  mutate(battletime = str_remove(battletime, "[:digit:]{4}-[:digit:]{2}-")) %>%
  mutate(battletime = as.numeric(battletime))
```


## mod11_CLAW_4001_6300 - s11, ComboLastActiveWin, 4001-6300
```{r}
# trophies ~ dayOfTheMonth + cards + levels + levels^2 + card interactions + day interact with lvl and lvl^2

preds <- predict(mod11_CLAW_4001_6300, cr[,-2])
df1 <- tibble(trophies = cr$startingtrophies, preds = preds)
df1 <-
  df1 %>%
  mutate(resid = trophies - preds)

df1 %>%
  ggplot(., aes(x = trophies, y = resid)) +
  geom_point() +
  geom_smooth() +
  labs(
    title = "Residuals vs Trophies (S11) Using 4001-6300 S11 Combined Last Active Win",
    subtitle = "trophies ~ dayOfTheMonth + cards + levels + levels^2 + card interactions + day:lvl & lvl^2"
    ) +
  theme_bw()
```








## df for 3rd model: 4001-6000
```{r}
# filter only the active players based on playertag
cr_sub <-
  df_combined %>%
    group_by(playertag) %>%
    filter(n() >= 25) %>% # define active
    filter(trophychange > 0) %>% # keep winned matches
    arrange(desc(battletime)) %>%
    slice(1) %>% # only take the last match for a player
    ungroup() #187,205




# reduce vars
cr_reduced <-
  cr_sub %>%
  select(playertag, battletime, startingtrophies, trophychange, deck)


set.seed(3007)
cr <- cr_reduced %>%
  #filter(battletime > '2020-05-29') %>% # only look at the last few days in the season
  #sample_n(tbl = ., size = 20000) %>% # random sample of 20k
  filter(str_count(deck, pattern = ",") == 15) # ensures 8 card decks



# fix card/level part
xcards <-
cr %>%  
  separate_rows(deck, sep = "\\],") %>%
  separate(deck, into = c("Cards","Level"), sep = ", ") %>%
  mutate(Level = parse_number(Level),
         Cards = str_remove_all(Cards, "\\[+"),
         Cards = str_remove_all(Cards, '\\"'),
         Cards = str_trim(Cards, side = c("both"))
         ) %>%
  left_join(., cr_cards, by = c("Cards" = "name")) %>% # add rarity info
  left_join(rarity, by = "rarity") %>% # add level adjustment
  mutate(Level = Level  + level_adjustment) %>% # adjust levels
  select(-rarity, -level_adjustment, -trophychange) # reduce size of dataframe

x = model.matrix(~0 + Cards + Level, model.frame(~ ., xcards, na.action=na.pass)) # make indictor variables

#x = xcards %>%  model.matrix(~0 + Cards + Level, data = .) 

x = sweep(x[,-ncol(x)], MARGIN = 1, STATS = x[,ncol(x)], FUN = "*")

colnames(x) = str_remove_all(colnames(x), "Cards")
colnames(x) = str_replace_all(colnames(x), " ", "_")
colnames(x) = str_replace_all(colnames(x), "-", "_")

# create names for all card and card interaction terms
interactions = labels(terms(~.^2, data = x[1:10,]))

colnames(x) = paste(colnames(x),"_Level",sep = "")

deck <- 
  x %>%
  as_tibble() %>%
  mutate(tmpid = xcards$playertag) %>%
  group_by(tmpid) %>%
  summarize_if(is.numeric, sum)

rm(x) # free up memory
rm(xcards)

# put back together
cr <- cr %>%
  select(battletime, startingtrophies) %>%
  bind_cols(sign(deck[,-1])) %>%
  bind_cols(deck[,-1])

rm(deck) # free memory from deck

names(cr) = str_remove_all(names(cr), "_Level") # fix anmes
names(cr) = str_replace_all(names(cr), "1","_Level") # one more fix



# filter 4000+
# and convert battletime -> day of the month
cr <-
  cr %>%
  filter(startingtrophies >= 4001 & startingtrophies < 6000) %>%
  mutate(battletime = str_remove(battletime, "\\s.+")) %>%
  mutate(battletime = str_remove(battletime, "[:digit:]{4}-[:digit:]{2}-")) %>%
  mutate(battletime = as.numeric(battletime))
```


## mod11_CLAW_4001_6000 - s11, ComboLastActiveWin, 4001-6000
```{r}
# trophies ~ dayOfTheMonth + cards + levels + levels^2 + card interactions + day interact with lvl and lvl^2

preds <- predict(mod11_CLAW_4001_6000, cr[,-2])
df1 <- tibble(trophies = cr$startingtrophies, preds = preds)
df1 <-
  df1 %>%
  mutate(resid = trophies - preds)

df1 %>%
  ggplot(., aes(x = trophies, y = resid)) +
  geom_point() +
  geom_smooth() +
  labs(
    title = "Residuals vs Trophies (S11) Using 4001-6000 S11 Combined Last Active Win",
    subtitle = "trophies ~ dayOfTheMonth + cards + levels + levels^2 + card interactions + day:lvl & lvl^2"
    ) +
  theme_bw()
```

















